// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfP7g6X0Hoikd0jeWOKT6UjOmwdCTVFk',
    appId: '1:421177428559:web:a8d2edf2159c323dca783a',
    messagingSenderId: '421177428559',
    projectId: 'expense-tracker-ca5d2',
    authDomain: 'expense-tracker-ca5d2.firebaseapp.com',
    storageBucket: 'expense-tracker-ca5d2.firebasestorage.app',
    measurementId: 'G-JJ2DRYXF08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfSYOxLkxeyy-rZAzVHHA7GP2CTKhFzI',
    appId: '1:421177428559:android:701639f92350f031ca783a',
    messagingSenderId: '421177428559',
    projectId: 'expense-tracker-ca5d2',
    storageBucket: 'expense-tracker-ca5d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ld73bajuPLbeGj5vHUFRWcKVADlr8g4',
    appId: '1:421177428559:ios:71da0995cbef6fddca783a',
    messagingSenderId: '421177428559',
    projectId: 'expense-tracker-ca5d2',
    storageBucket: 'expense-tracker-ca5d2.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ld73bajuPLbeGj5vHUFRWcKVADlr8g4',
    appId: '1:421177428559:ios:71da0995cbef6fddca783a',
    messagingSenderId: '421177428559',
    projectId: 'expense-tracker-ca5d2',
    storageBucket: 'expense-tracker-ca5d2.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjfP7g6X0Hoikd0jeWOKT6UjOmwdCTVFk',
    appId: '1:421177428559:web:5d2af2fbfaaf0f6fca783a',
    messagingSenderId: '421177428559',
    projectId: 'expense-tracker-ca5d2',
    authDomain: 'expense-tracker-ca5d2.firebaseapp.com',
    storageBucket: 'expense-tracker-ca5d2.firebasestorage.app',
    measurementId: 'G-KRWH7B4P22',
  );
}
