import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'data/dummy_data.dart';
import 'firebase_options.dart';
import 'models/category.dart';
import 'providers/expense_store.dart';
import 'screens/auth_screen.dart';
import 'screens/dashboard_shell.dart';
import 'screens/homepage_screen.dart';
import 'services/auth_service.dart';
import 'theme/app_theme.dart';
import 'widgets/auth_gate.dart';

/// Seed Category models from Stitch dummy data (cached in Provider per
/// AGENTS perf rule — never refetched per screen).
List<Category> seedCategories() => [
      for (var i = 0; i < dummyCategories.length; i++)
        Category(
          id: 'c${i + 1}',
          name: dummyCategories[i].name,
          monthlyLimit: dummyCategories[i].limit,
          colorValue: dummyCategories[i].color.toARGB32(),
          iconCodePoint: dummyCategories[i].icon.codePoint,
        ),
    ];

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    NdohApp(
      store: ExpenseStore(categories: seedCategories()),
      authService: AuthService(),
    ),
  );
}

/// Ndoh root. Navigation is auth-gated via [AuthGate], which listens to
/// [AuthService.authStateChanges] — never a one-time check.
/// NOTE: Firebase.initializeApp (firebase_options.dart, generated by
/// `flutterfire configure`) lands here once configuration is done.
class NdohApp extends StatelessWidget {
  const NdohApp({super.key, this.store, this.authService});

  final ExpenseStore? store;
  final AuthService? authService;

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<ExpenseStore>.value(
          value: store ?? ExpenseStore(categories: seedCategories()),
        ),
        ChangeNotifierProvider<AuthService>.value(
          value: authService ?? AuthService(),
        ),
      ],
      child: MaterialApp(
        title: 'Ndoh',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light(),
        home: const AuthGate(),
        routes: {
          '/home': (_) => const HomepageScreen(),
          '/auth': (_) => const AuthScreen(),
          '/dashboard': (_) => const DashboardShell(),
        },
      ),
    );
  }
}
